### Server Port ?? ###
server:
  port: 8000

### Spring ?? ###
spring:
  ### DataSource ?? ###
  datasource:
    # Driver
    driver-class-name: oracle.jdbc.driver.OracleDriver
    # DB URL
    url: jdbc:oracle:thin:@125.131.88.69:8200:orcl
    # DB ?? ???
    username: DT_PLAYGROUND
    # DB ?? ????
    password: dt1234
    tomcat:
      # ??? ???? ??? ? ?? ??(???)
      max-wait: 20000
      # ??? ?? ??? ???? ?? ??(DB ?? ?? ?)
      max-active: 50
      # ???? ?? ?? ??? ? ?? ???? ?? ??
      max-idle: 20
      # ???? ?? ?? ??? ? ?? ???? ?? ??
      min-idle: 15
  ### JPA ?? ###
  jpa:
    hibernate:
      # ???? ???? ?? ?? ?? ??(??)
      ddl-auto: none
    # DDL ?? ? ??????? ?? ??? ????? ??(DDL ??? ?? ???? ??? false)
    generate-ddl: false
    # jpa? ??? CRUD ?? ? ?? CRUD? SQL? ??? ??
    show-sql: true
    properties:
      hibernate:
        # ???? SQL? ?? ?? ??
        format_sql: true
        # ?????? ?? ??
        dialect: org.hibernate.dialect.Oracle10gDialect
  ### Thymeleaf ?? ###
  thymeleaf:
    # Thymeleaf ?? ??
    prefix: classpath:/templates/
    suffix: .html
    # Thymeleaf ?? ??? ??? ??? ??? ??, ??? ?? ??
    check-template-location: true
    # Thymeleaf? ?? ??? ??? ??
    cache: false

### MyBatis ?? ###
mybatis:
  # ??????? ?? ?? ???? ?? ????? ??? ??
  type-aliases-package: com.example.miniback.entity.*
  # mapper xml ?? ??
  mapper-locations: mapper/**/*.xml
  configuration:
    # model ???? camel case ??
    map-underscore-to-camel-case: true
  
### Log Message ?? ###
logging:
  level:
    org:
      hibernate:
        # hibernate? ?? SQL ?? ??
        SQL: DEBUG
        type:
          descriptor:
            sql:
              # hibernate? ???? ??? ?? ?? ?? ????? ??
              BasicBinder: TRACE

### JWT ?? ###
jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400